platform :ios, '15.0'

target 'App' do
  use_frameworks!

  # Capacitor Core
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  
  # Capacitor Plugins
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Fix for archive build - disable strict module header checking
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end
  end
  
  # Fix CocoaPods script bug with 'source' variable conflicting with bash builtin
  frameworks_script = File.join(installer.sandbox.root, 'Target Support Files/Pods-App/Pods-App-frameworks.sh')
  if File.exist?(frameworks_script)
    script_content = File.read(frameworks_script)
    script_content.gsub!(/^set -u$/, '# set -u  # Disabled due to CocoaPods bug')
    File.write(frameworks_script, script_content)
  end
end
